# Generated by Django 6.0.2 on 2026-02-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_mytest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
