# Generated by Django 6.0.2 on 2026-02-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_mytest', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
